
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IDENTIFIER PYTHON\n    root : expression\n    \n    expression : identifier PYTHON\n    \n    expression : expression identifier PYTHON\n    \n    identifier : identifier IDENTIFIER\n    \n    identifier : IDENTIFIER\n    '
    
_lr_action_items = {'IDENTIFIER':([0,2,3,4,5,6,7,8,],[4,4,7,-5,7,-2,-4,-3,]),'$end':([1,2,6,8,],[0,-1,-2,-3,]),'PYTHON':([3,4,5,7,],[6,-5,8,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'root':([0,],[1,]),'expression':([0,],[2,]),'identifier':([0,2,],[3,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> root","S'",1,None,None,None),
  ('root -> expression','root',1,'p_root','lib.py',45),
  ('expression -> identifier PYTHON','expression',2,'p_expression','lib.py',51),
  ('expression -> expression identifier PYTHON','expression',3,'p_expression_2','lib.py',59),
  ('identifier -> identifier IDENTIFIER','identifier',2,'p_identifier','lib.py',67),
  ('identifier -> IDENTIFIER','identifier',1,'p_identifier_2','lib.py',73),
]
