root : expression ';' root
;

expression : identifier '=' expression | term ('+' | '-') term
;

term : factor ("*" | "/") factor
;

factor : group
;

group : "(" expression ")" | identifier | number
;