
expression : term ';' 
    | term ';' expression
;

declaration : "var" identifier "=" expression
;

term : factor
    | term ("+" | "-") factor
;

factor : group ("*" | "/") group
;

group : "(" expression ")" | identifier | number
;


1 + 1 * 2 - 3
      |         