root : expression ';' root
;

expression : identifier '=' expression | term ('+' | '-') term
;

declaration : "var" identifier "=" expression
;

term : factor ("*" | "/") factor
;

factor : group ("*" | "/") group
;

group : "(" expression ")" | identifier | number
;